-- ============================================================================
-- PROJECT: 04-MiniERP-Manufacturing-Warehouse
-- FILE: sql/03_seed.sql
-- TARGET: Oracle Database 19c / 21c / 23c
-- DESCRIPTION: Master seed data representing a footwear & apparel manufacturer
-- ============================================================================

-- 1. Warehouses
INSERT INTO WAREHOUSE (CODE, NAME, LOCATION, IS_ACTIVE)
VALUES ('WH_RAW', 'Kho Nguyên Phụ Liệu - KCN Biên Hòa 2', 'Khu Công Nghiệp Biên Hòa 2, Đồng Nai', 1);

INSERT INTO WAREHOUSE (CODE, NAME, LOCATION, IS_ACTIVE)
VALUES ('WH_FG', 'Kho Thành Phẩm Xuất Khẩu', 'Cụm Kho Logistics Long Thành, Đồng Nai', 1);

INSERT INTO WAREHOUSE (CODE, NAME, LOCATION, IS_ACTIVE)
VALUES ('WH_WIP', 'Kho Bán Thành Phẩm Chuyền May', 'Xưởng Sản Xuất 1 - Tầng 2', 1);

-- 2. Items: Raw Materials (RAW)
INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('MAT_RUBBER_01', 'Đế cao su lưu hóa đúc sẵn (Size 42)', 'RAW', 'PAIR', 500);

INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('MAT_MESH_01', 'Vải lưới thoáng khí Jacquard Mesh Đen', 'RAW', 'METER', 200);

INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('MAT_THREAD_01', 'Chỉ may công nghiệp Polyester 40/2', 'RAW', 'SPOOL', 100);

INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('MAT_GLUE_01', 'Keo dán PU ngành giày dép chuyên dụng', 'RAW', 'KG', 50);

INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('MAT_BOX_01', 'Hộp carton đóng gói giày có in logo', 'RAW', 'PCS', 500);

-- Items: Finished Goods (FG)
INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('FG_RUNNER_PRO_42', 'Giày thể thao Runner Pro Đen Size 42', 'FG', 'PAIR', 100);

INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('FG_SNEAKER_LITE_40', 'Giày Sneaker Streetwear Trắng Size 40', 'FG', 'PAIR', 100);

-- 3. Bill of Materials (BOM) for FG_RUNNER_PRO_42
-- For 1 Pair of Shoes:
-- - 1 Pair MAT_RUBBER_01
-- - 0.5 Meter MAT_MESH_01
-- - 0.1 Spool MAT_THREAD_01
-- - 0.2 Kg MAT_GLUE_01
-- - 1 Pcs MAT_BOX_01
INSERT INTO BOM (FG_ITEM_ID, VERSION, DESCRIPTION, STATUS)
VALUES (
  (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42'),
  'V1.0',
  'Định mức chuẩn sản xuất Giày Runner Pro 2026',
  'ACTIVE'
);

INSERT INTO BOM_DETAIL (BOM_ID, MAT_ITEM_ID, QTY_REQUIRED)
VALUES (
  (SELECT ID FROM BOM WHERE VERSION = 'V1.0' AND FG_ITEM_ID = (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42')),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_RUBBER_01'),
  1
);

INSERT INTO BOM_DETAIL (BOM_ID, MAT_ITEM_ID, QTY_REQUIRED)
VALUES (
  (SELECT ID FROM BOM WHERE VERSION = 'V1.0' AND FG_ITEM_ID = (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42')),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_MESH_01'),
  0.5
);

INSERT INTO BOM_DETAIL (BOM_ID, MAT_ITEM_ID, QTY_REQUIRED)
VALUES (
  (SELECT ID FROM BOM WHERE VERSION = 'V1.0' AND FG_ITEM_ID = (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42')),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_THREAD_01'),
  0.1
);

INSERT INTO BOM_DETAIL (BOM_ID, MAT_ITEM_ID, QTY_REQUIRED)
VALUES (
  (SELECT ID FROM BOM WHERE VERSION = 'V1.0' AND FG_ITEM_ID = (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42')),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_GLUE_01'),
  0.2
);

INSERT INTO BOM_DETAIL (BOM_ID, MAT_ITEM_ID, QTY_REQUIRED)
VALUES (
  (SELECT ID FROM BOM WHERE VERSION = 'V1.0' AND FG_ITEM_ID = (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42')),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_BOX_01'),
  1
);

-- 4. Initial Stock in WH_RAW (Note: intentionally leave MAT_RUBBER_01 low for incident simulation)
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QTY, UPDATED_AT)
VALUES (
  (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_RUBBER_01'),
  40, -- Only 40 pairs in stock! If PO requests 50 pairs, it will fail!
  SYSDATE
);

INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QTY, UPDATED_AT)
VALUES (
  (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_MESH_01'),
  500,
  SYSDATE
);

INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QTY, UPDATED_AT)
VALUES (
  (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_THREAD_01'),
  200,
  SYSDATE
);

INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QTY, UPDATED_AT)
VALUES (
  (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_GLUE_01'),
  100,
  SYSDATE
);

INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QTY, UPDATED_AT)
VALUES (
  (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_BOX_01'),
  600,
  SYSDATE
);

-- Record Initial Transactions (opening balances)
-- One STOCK_IN ledger row per seeded STOCK row, so the audit trail always
-- reconciles with the stock balance: STOCK.QTY = SUM(INVENTORY_TRANSACTION.QTY).
DECLARE
  v_txn_cnt NUMBER := 0;
BEGIN
  FOR r IN (SELECT s.WAREHOUSE_ID, s.ITEM_ID, s.QTY
              FROM STOCK s
             WHERE NOT EXISTS (SELECT 1 FROM INVENTORY_TRANSACTION t
                                WHERE t.WAREHOUSE_ID = s.WAREHOUSE_ID
                                  AND t.ITEM_ID = s.ITEM_ID))
  LOOP
    INSERT INTO INVENTORY_TRANSACTION
      (TXN_TYPE, ITEM_ID, WAREHOUSE_ID, QTY, BALANCE_AFTER, REF_NO, CREATED_BY)
    VALUES
      ('STOCK_IN', r.ITEM_ID, r.WAREHOUSE_ID, r.QTY, r.QTY, 'INIT_BALANCE', 'admin');
    v_txn_cnt := v_txn_cnt + SQL%ROWCOUNT;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('>>> Opening-balance transactions created: ' || v_txn_cnt);
  COMMIT;
END;
/

-- 5. ERP Users & Roles (PBKDF2 hashes; PASSWORD is a non-credential migration marker)
INSERT INTO ERP_ROLE (NAME) VALUES ('ERP_ADMIN');
INSERT INTO ERP_ROLE (NAME) VALUES ('WAREHOUSE_OPERATOR');
INSERT INTO ERP_ROLE (NAME) VALUES ('PRODUCTION_OPERATOR');
INSERT INTO ERP_ROLE (NAME) VALUES ('ERP_SUPPORT');
INSERT INTO ERP_ROLE (NAME) VALUES ('VIEWER');
-- Legacy role names remain available for old automation fixtures.
INSERT INTO ERP_ROLE (NAME) VALUES ('PRODUCTION_PLANNER');
INSERT INTO ERP_ROLE (NAME) VALUES ('ERP_SUPPORT_SPECIALIST');

-- Demo passwords are documented in README and are intentionally not the
-- credential source: authentication reads PASSWORD_HASH only.
INSERT INTO APP_USER (USERNAME, FULLNAME, DEPT, PASSWORD, PASSWORD_HASH, PASSWORD_ITERATIONS, IS_ACTIVE)
VALUES ('admin', 'System Administrator', 'IT', 'MIGRATED',
        'pbkdf2$210000$Xw2Y6Z9o2E0pp0ieFkWd+w==$DTWNoSJAjM7C92LEH4jmh7rMg6IEcH5UnKFXhAGTTcA=', 210000, 1);

INSERT INTO APP_USER (USERNAME, FULLNAME, DEPT, PASSWORD, PASSWORD_HASH, PASSWORD_ITERATIONS, IS_ACTIVE)
VALUES ('tan.mai', 'Mai Nguyen Binh Tan', 'IT ERP Operation', 'MIGRATED',
        'pbkdf2$210000$58KXmCvGKqdk3Tc5HVVezg==$a9YfEdYqP7Kzf/vIFKm/6yt96krr8dDHXOGTGTBxCgE=', 210000, 1);

INSERT INTO APP_USER (USERNAME, FULLNAME, DEPT, PASSWORD, PASSWORD_HASH, PASSWORD_ITERATIONS, IS_ACTIVE)
VALUES ('planner01', 'Nguyen Van A - Kế Hoạch Sản Xuất', 'Production', 'MIGRATED',
        'pbkdf2$210000$ydaNkPq5+11LPo4gaAWRaA==$sII2Zjm6iJkkPOh6sHaC8WNTWw3BP1urfMwKToRmut8=', 210000, 1);

INSERT INTO APP_USER (USERNAME, FULLNAME, DEPT, PASSWORD, PASSWORD_HASH, PASSWORD_ITERATIONS, IS_ACTIVE)
VALUES ('warehouse01', 'Tran Thi B - Quản Lý Kho', 'Warehouse', 'MIGRATED',
        'pbkdf2$210000$DBlKF64G7FlW6MFxVaepkw==$wwqqIfayvGUWOIuJqqUIuxuym394cxCCWAvYbZG2h44=', 210000, 1);

INSERT INTO APP_USER (USERNAME, FULLNAME, DEPT, PASSWORD, PASSWORD_HASH, PASSWORD_ITERATIONS, IS_ACTIVE)
VALUES ('viewer01', 'Demo Viewer', 'Audit', 'MIGRATED',
        'pbkdf2$210000$ytYCp5m6h79C8ol2Q5Mrng==$VkKVPR6AIlGNaQ/gLpHCsPlYh8vVHUPnvus+c4iBhFs=', 210000, 1);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES ((SELECT ID FROM APP_USER WHERE USERNAME = 'admin'),
        (SELECT ID FROM ERP_ROLE WHERE NAME = 'ERP_ADMIN'));
INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES ((SELECT ID FROM APP_USER WHERE USERNAME = 'tan.mai'),
        (SELECT ID FROM ERP_ROLE WHERE NAME = 'ERP_SUPPORT'));
INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES ((SELECT ID FROM APP_USER WHERE USERNAME = 'planner01'),
        (SELECT ID FROM ERP_ROLE WHERE NAME = 'PRODUCTION_OPERATOR'));
INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES ((SELECT ID FROM APP_USER WHERE USERNAME = 'warehouse01'),
        (SELECT ID FROM ERP_ROLE WHERE NAME = 'WAREHOUSE_OPERATOR'));
INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES ((SELECT ID FROM APP_USER WHERE USERNAME = 'viewer01'),
        (SELECT ID FROM ERP_ROLE WHERE NAME = 'VIEWER'));

COMMIT;

-- 6. Replenishment parameters for the automation layer (ERP_AUTOMATION W3
--    rule engine: suggested = ADU * lead_days + safety - available).
--    Must run AFTER the ITEM INSERTs above; idempotent MERGE.
MERGE INTO ITEM t
USING (SELECT 'MAT_RUBBER_01' AS CODE, 500 AS RP, 50 AS SS, 30 AS ADU, 7 AS LT FROM DUAL UNION ALL
       SELECT 'MAT_MESH_01',   200, 20, 15, 5 FROM DUAL UNION ALL
       SELECT 'MAT_THREAD_01', 100, 10,  8, 3 FROM DUAL UNION ALL
       SELECT 'MAT_GLUE_01',    50,  5,  4, 3 FROM DUAL UNION ALL
       SELECT 'MAT_BOX_01',    500, 50, 40, 2 FROM DUAL) s
ON (t.CODE = s.CODE)
WHEN MATCHED THEN UPDATE
  SET t.REORDER_POINT   = s.RP,
      t.SAFETY_STOCK    = s.SS,
      t.AVG_DAILY_USAGE = s.ADU,
      t.LEAD_TIME_DAYS  = s.LT;

COMMIT;
