-- ============================================================================
-- PROJECT: 04-MiniERP-Manufacturing-Warehouse
-- FILE: sql/03_seed.sql
-- TARGET: Oracle Database 19c / 21c / 23c
-- DESCRIPTION: Master seed data representing a footwear & apparel manufacturer
-- ============================================================================

-- 1. Warehouses
INSERT INTO WAREHOUSE (CODE, NAME, LOCATION, IS_ACTIVE)
VALUES ('WH_RAW', 'Kho Nguyên Phụ Liệu - KCN Biên Hòa 2', 'Khu Công Nghiệp Biên Hòa 2, Đồng Nai', 1);

INSERT INTO WAREHOUSE (CODE, NAME, LOCATION, IS_ACTIVE)
VALUES ('WH_FG', 'Kho Thành Phẩm Xuất Khẩu', 'Cụm Kho Logistics Long Thành, Đồng Nai', 1);

INSERT INTO WAREHOUSE (CODE, NAME, LOCATION, IS_ACTIVE)
VALUES ('WH_WIP', 'Kho Bán Thành Phẩm Chuyền May', 'Xưởng Sản Xuất 1 - Tầng 2', 1);

-- 2. Items: Raw Materials (RAW)
INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('MAT_RUBBER_01', 'Đế cao su lưu hóa đúc sẵn (Size 42)', 'RAW', 'PAIR', 500);

INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('MAT_MESH_01', 'Vải lưới thoáng khí Jacquard Mesh Đen', 'RAW', 'METER', 200);

INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('MAT_THREAD_01', 'Chỉ may công nghiệp Polyester 40/2', 'RAW', 'SPOOL', 100);

INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('MAT_GLUE_01', 'Keo dán PU ngành giày dép chuyên dụng', 'RAW', 'KG', 50);

INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('MAT_BOX_01', 'Hộp carton đóng gói giày có in logo', 'RAW', 'PCS', 500);

-- Items: Finished Goods (FG)
INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('FG_RUNNER_PRO_42', 'Giày thể thao Runner Pro Đen Size 42', 'FG', 'PAIR', 100);

INSERT INTO ITEM (CODE, NAME, ITEM_TYPE, UOM, MIN_STOCK)
VALUES ('FG_SNEAKER_LITE_40', 'Giày Sneaker Streetwear Trắng Size 40', 'FG', 'PAIR', 100);

-- 3. Bill of Materials (BOM) for FG_RUNNER_PRO_42
-- For 1 Pair of Shoes:
-- - 1 Pair MAT_RUBBER_01
-- - 0.5 Meter MAT_MESH_01
-- - 0.1 Spool MAT_THREAD_01
-- - 0.2 Kg MAT_GLUE_01
-- - 1 Pcs MAT_BOX_01
INSERT INTO BOM (FG_ITEM_ID, VERSION, DESCRIPTION, STATUS)
VALUES (
  (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42'),
  'V1.0',
  'Định mức chuẩn sản xuất Giày Runner Pro 2026',
  'ACTIVE'
);

INSERT INTO BOM_DETAIL (BOM_ID, MAT_ITEM_ID, QTY_REQUIRED)
VALUES (
  (SELECT ID FROM BOM WHERE VERSION = 'V1.0' AND FG_ITEM_ID = (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42')),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_RUBBER_01'),
  1
);

INSERT INTO BOM_DETAIL (BOM_ID, MAT_ITEM_ID, QTY_REQUIRED)
VALUES (
  (SELECT ID FROM BOM WHERE VERSION = 'V1.0' AND FG_ITEM_ID = (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42')),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_MESH_01'),
  0.5
);

INSERT INTO BOM_DETAIL (BOM_ID, MAT_ITEM_ID, QTY_REQUIRED)
VALUES (
  (SELECT ID FROM BOM WHERE VERSION = 'V1.0' AND FG_ITEM_ID = (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42')),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_THREAD_01'),
  0.1
);

INSERT INTO BOM_DETAIL (BOM_ID, MAT_ITEM_ID, QTY_REQUIRED)
VALUES (
  (SELECT ID FROM BOM WHERE VERSION = 'V1.0' AND FG_ITEM_ID = (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42')),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_GLUE_01'),
  0.2
);

INSERT INTO BOM_DETAIL (BOM_ID, MAT_ITEM_ID, QTY_REQUIRED)
VALUES (
  (SELECT ID FROM BOM WHERE VERSION = 'V1.0' AND FG_ITEM_ID = (SELECT ID FROM ITEM WHERE CODE = 'FG_RUNNER_PRO_42')),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_BOX_01'),
  1
);

-- 4. Initial Stock in WH_RAW (Note: intentionally leave MAT_RUBBER_01 low for incident simulation)
INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QTY, UPDATED_AT)
VALUES (
  (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_RUBBER_01'),
  40, -- Only 40 pairs in stock! If PO requests 50 pairs, it will fail!
  SYSDATE
);

INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QTY, UPDATED_AT)
VALUES (
  (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_MESH_01'),
  500,
  SYSDATE
);

INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QTY, UPDATED_AT)
VALUES (
  (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_THREAD_01'),
  200,
  SYSDATE
);

INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QTY, UPDATED_AT)
VALUES (
  (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_GLUE_01'),
  100,
  SYSDATE
);

INSERT INTO STOCK (WAREHOUSE_ID, ITEM_ID, QTY, UPDATED_AT)
VALUES (
  (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'),
  (SELECT ID FROM ITEM WHERE CODE = 'MAT_BOX_01'),
  600,
  SYSDATE
);

-- Record Initial Transactions
INSERT INTO INVENTORY_TRANSACTION (TXN_TYPE, ITEM_ID, WAREHOUSE_ID, QTY, BALANCE_AFTER, REF_NO, CREATED_BY)
VALUES ('STOCK_IN', (SELECT ID FROM ITEM WHERE CODE = 'MAT_RUBBER_01'), (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'), 40, 40, 'INIT_BALANCE', 'admin');

INSERT INTO INVENTORY_TRANSACTION (TXN_TYPE, ITEM_ID, WAREHOUSE_ID, QTY, BALANCE_AFTER, REF_NO, CREATED_BY)
VALUES ('STOCK_IN', (SELECT ID FROM ITEM WHERE CODE = 'MAT_MESH_01'), (SELECT ID FROM WAREHOUSE WHERE CODE = 'WH_RAW'), 500, 500, 'INIT_BALANCE', 'admin');

-- 5. ERP Users & Roles
INSERT INTO ERP_ROLE (NAME) VALUES ('ERP_ADMIN');
INSERT INTO ERP_ROLE (NAME) VALUES ('WAREHOUSE_OPERATOR');
INSERT INTO ERP_ROLE (NAME) VALUES ('PRODUCTION_PLANNER');
INSERT INTO ERP_ROLE (NAME) VALUES ('ERP_SUPPORT_SPECIALIST');

INSERT INTO APP_USER (USERNAME, FULLNAME, DEPT, PASSWORD, IS_ACTIVE)
VALUES ('admin', 'System Administrator', 'IT', 'pbkdf2$hash$admin123', 1);

INSERT INTO APP_USER (USERNAME, FULLNAME, DEPT, PASSWORD, IS_ACTIVE)
VALUES ('tan.mai', 'Mai Nguyen Binh Tan', 'IT ERP Operation', 'pbkdf2$hash$tan123', 1);

INSERT INTO APP_USER (USERNAME, FULLNAME, DEPT, PASSWORD, IS_ACTIVE)
VALUES ('planner01', 'Nguyen Van A - Kế Hoạch Sản Xuất', 'Production', 'pbkdf2$hash$plan123', 1);

INSERT INTO APP_USER (USERNAME, FULLNAME, DEPT, PASSWORD, IS_ACTIVE)
VALUES ('warehouse01', 'Tran Thi B - Quản Lý Kho', 'Warehouse', 'pbkdf2$hash$wh123', 1);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES (
  (SELECT ID FROM APP_USER WHERE USERNAME = 'tan.mai'),
  (SELECT ID FROM ERP_ROLE WHERE NAME = 'ERP_SUPPORT_SPECIALIST')
);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
VALUES (
  (SELECT ID FROM APP_USER WHERE USERNAME = 'planner01'),
  (SELECT ID FROM ERP_ROLE WHERE NAME = 'PRODUCTION_PLANNER')
);

COMMIT;
