-- ============================================================================
-- PROJECT: 04-MiniERP-Manufacturing-Warehouse
-- FILE: sql/05_automation_schema.sql
-- TARGET: Oracle Database 19c / 21c / 23c
-- DESCRIPTION: Persistence layer for the business-process automation layer:
--              material check + soft reservation, replenishment alerts,
--              automation-run audit (ERP_AUTOMATION_RUN), PO state history,
--              support incidents, approval gate, scheduled reports.
--              Every DDL statement is existence-guarded => rerunnable.
--              Load order (scripts/run-sql.sh):
--                01_schema -> 05_automation_schema -> 02_plsql
--                -> 06_automation_plsql -> 03_seed (-> 04_incident_scenarios)
-- ============================================================================

-- 5.1 Widen the PRODUCTION_ORDER lifecycle used by the automation layer.
--     Legacy states stay valid (ERP_OPERATIONS still writes RELEASED on
--     create and COMPLETED/CANCELLED on close). New states:
--       MATERIAL_CHECK   material availability check in evaluation
--       WAITING_MATERIAL check finished: >= 1 material is short
--       READY            all materials verified / soft-reserved
--       IN_PROGRESS      completion wrapper running (transient)
--     STATUS is widened to VARCHAR2(20): 'WAITING_MATERIAL' is 16 chars.
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt
    FROM user_constraints
   WHERE table_name = 'PRODUCTION_ORDER'
     AND constraint_name = 'CK_PO_STATUS';
  IF v_cnt > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTION_ORDER DROP CONSTRAINT CK_PO_STATUS';
  END IF;
END;
/

ALTER TABLE PRODUCTION_ORDER ADD CONSTRAINT CK_PO_STATUS CHECK (STATUS IN (
  'CREATED', 'RELEASED', 'MATERIAL_CHECK', 'WAITING_MATERIAL', 'READY',
  'IN_PROGRESS', 'COMPLETED', 'CANCELLED'
));

-- 5.1.1 Widen STATUS to accommodate new automation states (WAITING_MATERIAL=16 chars).
--     The check constraint above defines the legal values; this statement raises the
--     column width so INSERT/UPDATE never fail with ORA-12899.
DECLARE
  v_len NUMBER;
BEGIN
  SELECT data_length INTO v_len
    FROM user_tab_columns
   WHERE table_name = 'PRODUCTION_ORDER' AND column_name = 'STATUS';
  IF v_len < 20 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCTION_ORDER MODIFY STATUS VARCHAR2(20)';
  END IF;
END;
/

-- 5.2 Extend ITEM with replenishment parameters (inputs of the W3 rule:
--     suggested = AVG_DAILY_USAGE * LEAD_TIME_DAYS + SAFETY_STOCK - available).
--     NOT NULL DEFAULT 0 keeps every existing INSERT working unchanged;
--     sql/03_seed.sql backfills the demo catalogue (it runs after this file).
DECLARE
  PROCEDURE add_col(p_col VARCHAR2, p_def VARCHAR2) IS
    v_cnt NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_cnt
      FROM user_tab_columns
     WHERE table_name = 'ITEM' AND column_name = p_col;
    IF v_cnt = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ITEM ADD (' || p_col || ' ' || p_def || ')';
    END IF;
  END add_col;
BEGIN
  add_col('REORDER_POINT',   'NUMBER DEFAULT 0 NOT NULL');
  add_col('SAFETY_STOCK',    'NUMBER DEFAULT 0 NOT NULL');
  add_col('AVG_DAILY_USAGE', 'NUMBER DEFAULT 0 NOT NULL');
  add_col('LEAD_TIME_DAYS',  'NUMBER DEFAULT 0 NOT NULL');
END;
/

-- 5.3 STOCK_RESERVATION: soft hold of material for a production order.
--     Physical STOCK rows are untouched; availability is computed as
--     STOCK.QTY - SUM(ACTIVE holds of *other* orders).
--     ON DELETE CASCADE keeps cleanup automatic with the PO001 scenario.
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'STOCK_RESERVATION';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE STOCK_RESERVATION (
        ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        PO_NO        VARCHAR2(30) NOT NULL
                     CONSTRAINT FK_RES_PO REFERENCES PRODUCTION_ORDER(PO_NO) ON DELETE CASCADE,
        ITEM_ID      NUMBER NOT NULL CONSTRAINT FK_RES_ITEM REFERENCES ITEM(ID),
        WAREHOUSE_ID NUMBER NOT NULL CONSTRAINT FK_RES_WH   REFERENCES WAREHOUSE(ID),
        QTY          NUMBER NOT NULL CONSTRAINT CK_RES_QTY  CHECK (QTY > 0),
        STATUS       VARCHAR2(15) DEFAULT 'ACTIVE' NOT NULL
                     CONSTRAINT CK_RES_STATUS CHECK (STATUS IN ('ACTIVE', 'RELEASED', 'CONSUMED')),
        CREATED_AT   DATE DEFAULT SYSDATE NOT NULL,
        UPDATED_AT   DATE DEFAULT SYSDATE NOT NULL
      )]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IX_RES_AVAIL';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_RES_AVAIL ON STOCK_RESERVATION (ITEM_ID, WAREHOUSE_ID, STATUS)';
  END IF;
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IX_RES_PO';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_RES_PO ON STOCK_RESERVATION (PO_NO, STATUS)';
  END IF;
END;
/

-- 5.4 REPLENISH_ALERT: low-stock / shortage alert raised by W1 and W3.
--     One OPEN row per (item, warehouse); closed when the position recovers.
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'REPLENISH_ALERT';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE REPLENISH_ALERT (
        ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ITEM_ID       NUMBER NOT NULL CONSTRAINT FK_ALERT_ITEM REFERENCES ITEM(ID),
        WAREHOUSE_ID  NUMBER NOT NULL CONSTRAINT FK_ALERT_WH   REFERENCES WAREHOUSE(ID),
        QTY_AVAILABLE NUMBER DEFAULT 0 NOT NULL,
        QTY_SUGGESTED NUMBER DEFAULT 0 NOT NULL,
        TRIGGER_TYPE  VARCHAR2(20) DEFAULT 'LOW_STOCK' NOT NULL
                      CONSTRAINT CK_ALERT_TRG CHECK (TRIGGER_TYPE IN
                        ('LOW_STOCK', 'PO_SHORTAGE', 'MANUAL', 'SWEEP')),
        REF_NO        VARCHAR2(50),
        STATUS        VARCHAR2(15) DEFAULT 'OPEN' NOT NULL
                      CONSTRAINT CK_ALERT_STATUS CHECK (STATUS IN
                        ('OPEN', 'ACKNOWLEDGED', 'CLOSED')),
        TRIGGERED_BY  VARCHAR2(50) DEFAULT 'system' NOT NULL,
        CREATED_AT    DATE DEFAULT SYSDATE NOT NULL,
        CLOSED_AT     DATE
      )]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IX_ALERT_OPEN';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_ALERT_OPEN ON REPLENISH_ALERT (STATUS, ITEM_ID, WAREHOUSE_ID)';
  END IF;
END;
/

-- 5.5 ERP_AUTOMATION_RUN: audit trail of every automation workflow run.
--     STATUS: PENDING / RUNNING / SUCCESS / FAILED / MANUAL_REVIEW.
--     TRIGGER_TYPE: MANUAL (API call) / SCHEDULED (job) / EVENT (state change).
--     Written exclusively by the autonomous write_run helper of package
--     ERP_AUTOMATION => FAILED rows survive the workflow ROLLBACK.
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'ERP_AUTOMATION_RUN';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE ERP_AUTOMATION_RUN (
        ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        WORKFLOW_NAME  VARCHAR2(40) NOT NULL,
        TRIGGER_TYPE   VARCHAR2(20) DEFAULT 'MANUAL' NOT NULL
                       CONSTRAINT CK_RUN_TRIGGER CHECK (TRIGGER_TYPE IN
                         ('MANUAL', 'SCHEDULED', 'EVENT')),
        TRIGGER_ID     VARCHAR2(50),
        STATUS         VARCHAR2(15) DEFAULT 'PENDING' NOT NULL
                       CONSTRAINT CK_RUN_STATUS CHECK (STATUS IN
                         ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'MANUAL_REVIEW')),
        STARTED_AT     DATE DEFAULT SYSDATE NOT NULL,
        FINISHED_AT    DATE,
        RETRY_COUNT    NUMBER DEFAULT 0 NOT NULL,
        ERROR_CODE     VARCHAR2(30),
        ERROR_MESSAGE  VARCHAR2(2000),
        RESULT_SUMMARY VARCHAR2(2000),
        RUN_BY         VARCHAR2(50) DEFAULT 'system' NOT NULL
      )]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IX_RUN_WORKFLOW';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_RUN_WORKFLOW ON ERP_AUTOMATION_RUN (WORKFLOW_NAME, STARTED_AT)';
  END IF;
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IX_RUN_STATUS';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_RUN_STATUS ON ERP_AUTOMATION_RUN (STATUS, STARTED_AT)';
  END IF;
END;
/

-- 5.6 PO_STATE_HISTORY: every PRODUCTION_ORDER status transition, written by
--     trigger TRG_PO_STATE_HISTORY below. W5 stale detection reads it.
--     No FK on PO_NO on purpose: history must survive PO deletion (PO001
--     scenario resets delete and recreate the order on every run).
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'PO_STATE_HISTORY';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE PO_STATE_HISTORY (
        ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        PO_NO       VARCHAR2(30) NOT NULL,
        FROM_STATE  VARCHAR2(20),
        TO_STATE    VARCHAR2(20) NOT NULL,
        REASON      VARCHAR2(200),
        CHANGED_BY  VARCHAR2(50) DEFAULT 'system' NOT NULL,
        CHANGED_AT  DATE DEFAULT SYSDATE NOT NULL
      )]';
  END IF;
END;
/

-- 5.6.1 Widen state columns to accommodate new automation states.
DECLARE
  v_len_from NUMBER;
  v_len_to   NUMBER;
BEGIN
  SELECT data_length INTO v_len_from
    FROM user_tab_columns
   WHERE table_name = 'PO_STATE_HISTORY' AND column_name = 'FROM_STATE';
  SELECT data_length INTO v_len_to
    FROM user_tab_columns
   WHERE table_name = 'PO_STATE_HISTORY' AND column_name = 'TO_STATE';
  IF v_len_from < 20 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PO_STATE_HISTORY MODIFY FROM_STATE VARCHAR2(20)';
  END IF;
  IF v_len_to < 20 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PO_STATE_HISTORY MODIFY TO_STATE VARCHAR2(20)';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IX_HIST_PO';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_HIST_PO ON PO_STATE_HISTORY (PO_NO, CHANGED_AT)';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PO_STATE_HISTORY
AFTER UPDATE OF STATUS ON PRODUCTION_ORDER
FOR EACH ROW
WHEN (NEW.STATUS <> OLD.STATUS)
BEGIN
  INSERT INTO PO_STATE_HISTORY (PO_NO, FROM_STATE, TO_STATE, REASON, CHANGED_BY)
  VALUES (:OLD.PO_NO, :OLD.STATUS, :NEW.STATUS, 'status-transition', 'system');
END;
/

-- 5.7 SUPPORT_INCIDENT: incident context snapshot collected by W7
--     (ERROR_LOG rows + PO state + open alerts as JSON + rule diagnosis).
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'SUPPORT_INCIDENT';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE SUPPORT_INCIDENT (
        ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ERROR_CODE   VARCHAR2(30) NOT NULL,
        REF_NO       VARCHAR2(50),
        TITLE        VARCHAR2(200) NOT NULL,
        CONTEXT_JSON VARCHAR2(4000),
        DIAGNOSIS    VARCHAR2(1000),
        STATUS       VARCHAR2(15) DEFAULT 'OPEN' NOT NULL
                     CONSTRAINT CK_INC_STATUS CHECK (STATUS IN
                       ('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED')),
        CREATED_BY   VARCHAR2(50) DEFAULT 'system' NOT NULL,
        CREATED_AT   DATE DEFAULT SYSDATE NOT NULL,
        CLOSED_AT    DATE
      )]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IX_INC_REF';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_INC_REF ON SUPPORT_INCIDENT (REF_NO, STATUS)';
  END IF;
END;
/

-- 5.8 APPROVAL_REQUEST: human approval gate for risky automation overrides
--     (W7 adjust_stock consumes an APPROVED token of action INVENTORY_ADJUST).
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'APPROVAL_REQUEST';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE APPROVAL_REQUEST (
        ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        APPROVAL_NO  VARCHAR2(30) NOT NULL UNIQUE,
        ACTION       VARCHAR2(40) NOT NULL
                     CONSTRAINT CK_APV_ACTION CHECK (ACTION IN
                       ('INVENTORY_ADJUST', 'COMPLETE_OVERRIDE',
                        'BOM_FORCE_SAVE', 'STOCK_OVERRIDE')),
        REF_NO       VARCHAR2(50),
        PAYLOAD      VARCHAR2(2000),
        STATUS       VARCHAR2(15) DEFAULT 'PENDING' NOT NULL
                     CONSTRAINT CK_APV_STATUS CHECK (STATUS IN
                       ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'EXECUTED')),
        REQUESTER    VARCHAR2(50),
        APPROVER     VARCHAR2(50),
        DECIDED_AT   DATE,
        CREATED_AT   DATE DEFAULT SYSDATE NOT NULL
      )]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IX_APV_STATUS';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_APV_STATUS ON APPROVAL_REQUEST (STATUS, ACTION)';
  END IF;
END;
/

-- 5.9 AUTOMATION_REPORT: persisted snapshot of a scheduled operational report
--     generated by W6 (JSON payload capped at 4000 chars).
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'AUTOMATION_REPORT';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE AUTOMATION_REPORT (
        ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        REPORT_TYPE  VARCHAR2(30) NOT NULL
                     CONSTRAINT CK_REP_TYPE CHECK (REPORT_TYPE IN
                       ('INVENTORY_SNAPSHOT', 'LOW_STOCK', 'PO_BY_STATUS',
                        'COMPLETED_PRODUCTION', 'STOCK_MOVEMENTS', 'FAILED_OPERATIONS')),
        PERIOD_FROM  DATE,
        PERIOD_TO    DATE DEFAULT SYSDATE,
        LINE_COUNT   NUMBER DEFAULT 0 NOT NULL,
        PAYLOAD_JSON VARCHAR2(4000),
        GENERATED_BY VARCHAR2(50) DEFAULT 'system' NOT NULL,
        GENERATED_AT DATE DEFAULT SYSDATE NOT NULL
      )]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IX_REP_TYPE';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_REP_TYPE ON AUTOMATION_REPORT (REPORT_TYPE, GENERATED_AT)';
  END IF;
END;
/

COMMIT;

-- ============================================================================
-- end of sql/05_automation_schema.sql
-- ============================================================================