-- ============================================================================
-- PROJECT: 04-MiniERP-Manufacturing-Warehouse
-- FILE: sql/10_helpdesk_schema.sql
-- TARGET: Oracle Database 19c / 21c / 23c
-- DESCRIPTION: Phase 7 idempotent Helpdesk delivery outbox. Additive and rerunnable.
-- Load order: after sql/09_traceability_seed.sql (see scripts/run-sql.sh).
-- ============================================================================

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'HELPDESK_DELIVERY';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE HELPDESK_DELIVERY (
        DELIVERY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        EXTERNAL_REF VARCHAR2(80) NOT NULL UNIQUE,
        OPERATION VARCHAR2(40) DEFAULT 'INCIDENT' NOT NULL,
        REQUEST_HASH VARCHAR2(64) NOT NULL,
        STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
          CONSTRAINT CK_HD_STATUS CHECK (STATUS IN
            ('PENDING','SENT','FAILED','NOT_ENABLED','CONFLICT')),
        ATTEMPT_COUNT NUMBER DEFAULT 0 NOT NULL,
        LAST_ERROR VARCHAR2(1000),
        CORRELATION_ID VARCHAR2(60),
        CREATED_BY VARCHAR2(50) DEFAULT 'system' NOT NULL,
        CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
        UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
        SENT_AT DATE
      )]';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IX_HD_STATUS';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_HD_STATUS ON HELPDESK_DELIVERY (STATUS, UPDATED_AT)';
  END IF;
END;
/

COMMIT;
